id = "bfd3"
name = "BFD3 Drums"
notes = [
  { note = 18, canon = "hat.cc.tip", primary = true },
  { note = 20, canon = "hat.cc.edge", primary = true },
  { note = 22, canon = "hat.cc.bell", primary = true },
  { note = 24, canon = "kick.main", primary = true },
  { note = 25, canon = "snare1.sidestick", primary = true },
  { note = 26, canon = "snare1.hit", primary = true },
  { note = 27, canon = "snare1.ruff", primary = true },
  { note = 28, canon = "snare1.hit" },
  { note = 29, canon = "snare1.rimshot", primary = true },
  { note = 30, canon = "hat.closed.tip", primary = true },
  { note = 31, canon = "tom.floor1.hit", primary = true },
  { note = 32, canon = "hat.pedal", primary = true },
  { note = 33, canon = "tom.floor2.hit", primary = true },
  { note = 34, canon = "hat.open3.tip", primary = true },
  { note = 35, canon = "tom.rack3.hit", primary = true },
  { note = 36, canon = "tom.rack4.hit", primary = true },
  { note = 37, canon = "hat.closed.edge", primary = true },
  { note = 38, canon = "tom.rack1.hit", primary = true },
  { note = 39, canon = "hat.open3.tip" },
  { note = 40, canon = "tom.rack2.hit", primary = true },
  { note = 41, canon = "crash.1.hit" },
  { note = 42, canon = "hat.loose.tip", primary = true },
  { note = 43, canon = "crash.2.hit" },
  { note = 44, canon = "hat.loose.edge", primary = true },
  { note = 45, canon = "ride.1.edge" },
  { note = 46, canon = "hat.open1.tip", primary = true },
  { note = 47, canon = "crash.3.hit" },
  { note = 48, canon = "crash.4.hit" },
  { note = 49, canon = "hat.open1.edge", primary = true },
  { note = 50, canon = "ride.2.edge" },
  { note = 51, canon = "hat.open2.tip", primary = true },
  { note = 52, canon = "crash.1.bowtip", primary = true },
  { note = 53, canon = "crash.2.bowtip", primary = true },
  { note = 54, canon = "hat.open2.edge", primary = true },
  { note = 55, canon = "ride.1", primary = true },
  { note = 56, canon = "hat.pedalsplash", primary = true },
  { note = 57, canon = "crash.3.bow", primary = true },
  { note = 58, canon = "hat.closed.bell", primary = true },
  { note = 59, canon = "crash.4.bow", primary = true },
  { note = 60, canon = "ride.2", primary = true },
  { note = 61, canon = "tom.floor1.rimshot", primary = true },
  { note = 62, canon = "crash.1.bell", primary = true },
  { note = 63, canon = "tom.floor2.rimshot", primary = true },
  { note = 64, canon = "crash.2.bell", primary = true },
  { note = 65, canon = "ride.1.bell", primary = true },
  { note = 66, canon = "tom.rack3.rimshot", primary = true },
  { note = 67, canon = "crash.3.bell", primary = true },
  { note = 68, canon = "tom.rack4.rimshot", primary = true },
  { note = 69, canon = "crash.4.bell", primary = true },
  { note = 70, canon = "tom.rack1.rimshot", primary = true },
  { note = 71, canon = "ride.2.bell", primary = true },
  { note = 72, canon = "crash.1.hit", primary = true },
  { note = 73, canon = "tom.rack2.rimshot", primary = true },
  { note = 74, canon = "crash.2.hit", primary = true },
  { note = 75, canon = "crash.1.mute", primary = true },
  { note = 76, canon = "ride.1.edge", primary = true },
  { note = 77, canon = "crash.3.hit", primary = true },
  { note = 78, canon = "crash.2.mute", primary = true },
  { note = 79, canon = "crash.4.hit", primary = true },
  { note = 80, canon = "ride.1.mute", primary = true },
  { note = 81, canon = "ride.2.edge", primary = true },
  { note = 82, canon = "crash.3.mute", primary = true },
  { note = 83, canon = "perc.clap", primary = true },
  { note = 84, canon = "kick.main" },
  { note = 85, canon = "crash.4.mute", primary = true },
  { note = 86, canon = "snare1.flam", primary = true },
  { note = 87, canon = "ride.2.mute", primary = true },
  { note = 88, canon = "snare1.rim", primary = true },
  { note = 89, canon = "tom.floor1.rim", primary = true },
  { note = 90, canon = "tom.floor2.rim", primary = true },
  { note = 91, canon = "tom.rack3.rim", primary = true },
  { note = 92, canon = "tom.rack4.rim", primary = true },
  { note = 93, canon = "tom.rack1.rim", primary = true },
  { note = 94, canon = "tom.rack2.rim", primary = true },
  { note = 95, canon = "perc.misc", primary = true },
]
