id = "bogren_krimh"
name = "Bogren Digital Krimh Drums"
notes = [
  { note = 17, canon = "hat.cc", primary = true },
  { note = 22, canon = "kick.main" },
  { note = 23, canon = "kick.left", primary = true },
  { note = 24, canon = "kick.main", primary = true },
  { note = 25, canon = "snare1.side", primary = true },
  { note = 26, canon = "snare1.hit", primary = true },
  { note = 27, canon = "snare1.flam", primary = true },
  { note = 29, canon = "snare1.off", primary = true },
  { note = 30, canon = "snare1.sidestick", primary = true },
  { note = 33, canon = "tom.rack1.hit", primary = true },
  { note = 34, canon = "tom.rack2.hit", primary = true },
  { note = 35, canon = "tom.floor1.hit", primary = true },
  { note = 36, canon = "tom.floor2.hit", primary = true },
  { note = 37, canon = "tom.floor3.hit", primary = true },
  { note = 41, canon = "hat.closed.tip", primary = true },
  { note = 42, canon = "hat.closed.edge", primary = true },
  { note = 43, canon = "hat.open1", primary = true },
  { note = 44, canon = "hat.open2", primary = true },
  { note = 45, canon = "hat.open3", primary = true },
  { note = 46, canon = "hat.open4", primary = true },
  { note = 47, canon = "hat.open5", primary = true },
  { note = 48, canon = "hat.pedal", primary = true },
  { note = 49, canon = "hat.pedalsplash", primary = true },
  { note = 50, canon = "hat.open1.tip", primary = true },
  { note = 52, canon = "crash.1.hit", primary = true },
  { note = 53, canon = "crash.1.mute", primary = true },
  { note = 54, canon = "crash.3.hit", primary = true },
  { note = 55, canon = "crash.3.mute", primary = true },
  { note = 56, canon = "crash.2.hit", primary = true },
  { note = 57, canon = "crash.2.mute", primary = true },
  { note = 58, canon = "crash.4.hit", primary = true },
  { note = 59, canon = "crash.4.mute", primary = true },
  { note = 61, canon = "ride.1.bell", primary = true },
  { note = 62, canon = "ride.1", primary = true },
  { note = 63, canon = "ride.1.edge", primary = true },
  { note = 65, canon = "china.1.hit", primary = true },
  { note = 66, canon = "china.1.mute", primary = true },
  { note = 67, canon = "china.2.hit", primary = true },
  { note = 68, canon = "china.2.mute", primary = true },
  { note = 70, canon = "aux1.closed" },
  { note = 71, canon = "aux1.open5" },
  { note = 73, canon = "splash.1.hit", primary = true },
  { note = 74, canon = "splash.1.mute", primary = true },
  { note = 75, canon = "splash.2.hit", primary = true },
  { note = 76, canon = "splash.2.mute", primary = true },
  { note = 82, canon = "aux1.closed", primary = true },
  { note = 83, canon = "aux1.open1", primary = true },
  { note = 84, canon = "aux1.open2", primary = true },
  { note = 85, canon = "aux1.open3", primary = true },
  { note = 86, canon = "aux1.open4", primary = true },
  { note = 87, canon = "aux1.open5", primary = true },
  { note = 88, canon = "aux1.open6", primary = true },
]
