id = "drumforge_greiner"
name = "Drumforge Matt Greiner"
notes = [
  { note = 34, canon = "snare1.rim", primary = true },
  { note = 35, canon = "snare1.sidestick", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "kick.main" },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "snare1.hit" },
  { note = 40, canon = "tom.rack1.hit", primary = true },
  { note = 41, canon = "tom.rack2.hit", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 44, canon = "tom.rack1.hit" },
  { note = 45, canon = "tom.rack2.hit" },
  { note = 47, canon = "tom.floor1.hit" },
  { note = 50, canon = "hat.open4", primary = true },
  { note = 51, canon = "hat.open3", primary = true },
  { note = 52, canon = "hat.open2", primary = true },
  { note = 53, canon = "hat.open1", primary = true },
  { note = 54, canon = "hat.pedal", primary = true },
  { note = 55, canon = "hat.closed.edge", primary = true },
  { note = 56, canon = "hat.closed.tip", primary = true },
  { note = 57, canon = "hat.tight.edge", primary = true },
  { note = 58, canon = "hat.tight.tip", primary = true },
  { note = 60, canon = "crash.1.hit", primary = true },
  { note = 61, canon = "crash.1.mute", primary = true },
  { note = 62, canon = "crash.2.hit", primary = true },
  { note = 63, canon = "crash.2.mute", primary = true },
  { note = 67, canon = "ride.1.bowtip", primary = true },
  { note = 68, canon = "ride.1", primary = true },
  { note = 69, canon = "ride.1.bell", primary = true },
  { note = 70, canon = "ride.1.belltip", primary = true },
  { note = 77, canon = "china.1.hit", primary = true },
  { note = 78, canon = "china.1.mute", primary = true },
  { note = 79, canon = "splash.1.hit", primary = true },
  { note = 80, canon = "splash.1.mute", primary = true },
  { note = 81, canon = "china.2.hit", primary = true },
  { note = 82, canon = "china.2.mute", primary = true },
  { note = 83, canon = "bell.1.hit", primary = true },
  { note = 84, canon = "bell.1.hit" },
  { note = 85, canon = "bell.1.mute", primary = true },
  { note = 86, canon = "bell.2.hit", primary = true },
  { note = 87, canon = "bell.2.hit" },
  { note = 88, canon = "bell.2.mute", primary = true },
  { note = 89, canon = "stack.1.hit", primary = true },
  { note = 90, canon = "stack.1.mute", primary = true },
]
