id = "eastwest_prodrummer"
name = "EastWest ProDrummer"
notes = [
  { note = 34, canon = "hat.pedal", primary = true },
  { note = 35, canon = "kick.main" },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "snare1.flam", primary = true },
  { note = 40, canon = "snare1.rimshot" },
  { note = 41, canon = "tom.floor1.hit", primary = true },
  { note = 42, canon = "hat.closed", primary = true },
  { note = 43, canon = "tom.rack1.hit", primary = true },
  { note = 44, canon = "hat.open1", primary = true },
  { note = 45, canon = "tom.rack2.hit", primary = true },
  { note = 46, canon = "hat.open2", primary = true },
  { note = 47, canon = "tom.floor1.hit" },
  { note = 48, canon = "tom.rack1.hit" },
  { note = 49, canon = "hat.closed" },
  { note = 50, canon = "tom.rack2.hit" },
  { note = 51, canon = "ride.1.bell", primary = true },
  { note = 52, canon = "ride.1", primary = true },
  { note = 53, canon = "ride.1.mute", primary = true },
  { note = 54, canon = "crash.1.hit" },
  { note = 55, canon = "crash.1.mute" },
  { note = 56, canon = "crash.2.hit" },
  { note = 57, canon = "crash.2.mute" },
  { note = 58, canon = "hat.pedalsplash", primary = true },
  { note = 59, canon = "kick.main" },
  { note = 60, canon = "kick.main" },
  { note = 61, canon = "snare1.rimshot", primary = true },
  { note = 62, canon = "snare1.hit" },
  { note = 63, canon = "snare1.ruff", primary = true },
  { note = 64, canon = "snare1.ruff" },
  { note = 65, canon = "tom.floor1.rimshot", primary = true },
  { note = 66, canon = "hat.closed.edge", primary = true },
  { note = 67, canon = "tom.rack1.rimshot", primary = true },
  { note = 68, canon = "hat.open1" },
  { note = 69, canon = "tom.rack2.rimshot", primary = true },
  { note = 70, canon = "hat.open2" },
  { note = 71, canon = "tom.floor1.rimshot" },
  { note = 72, canon = "tom.rack1.rimshot" },
  { note = 73, canon = "hat.closed" },
  { note = 74, canon = "tom.rack2.rimshot" },
  { note = 75, canon = "ride.1.bell" },
  { note = 76, canon = "ride.1.edge", primary = true },
  { note = 77, canon = "ride.1.mute" },
  { note = 78, canon = "crash.1.hit", primary = true },
  { note = 79, canon = "crash.1.mute", primary = true },
  { note = 80, canon = "crash.2.hit", primary = true },
  { note = 81, canon = "crash.2.mute", primary = true },
]
