id = "fotis_benardo"
name = "Fotis Benardo Drums (Stigmatized Productions)"
notes = [
  { note = 24, canon = "crash.1.mute", primary = true },
  { note = 25, canon = "crash.2.mute", primary = true },
  { note = 26, canon = "crash.3.mute", primary = true },
  { note = 27, canon = "splash.1.mute", primary = true },
  { note = 28, canon = "china.1.mute", primary = true },
  { note = 29, canon = "ride.1.mute", primary = true },
  { note = 35, canon = "kick.left", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.rimshot", primary = true },
  { note = 39, canon = "snare1.rimshot" },
  { note = 40, canon = "snare1.rimshot" },
  { note = 41, canon = "snare1.hit", primary = true },
  { note = 42, canon = "hat.closed", primary = true },
  { note = 43, canon = "tom.floor2.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 45, canon = "tom.floor1.hit", primary = true },
  { note = 46, canon = "hat.open1", primary = true },
  { note = 47, canon = "tom.rack3.hit", primary = true },
  { note = 48, canon = "tom.rack2.hit", primary = true },
  { note = 49, canon = "hat.open2", primary = true },
  { note = 50, canon = "tom.rack1.hit", primary = true },
  { note = 51, canon = "hat.pedalsplash", primary = true },
  { note = 52, canon = "hat.tight.tip", primary = true },
  { note = 53, canon = "hat.closed.tip", primary = true },
  { note = 54, canon = "hat.loose.tip", primary = true },
  { note = 55, canon = "hat.loose", primary = true },
  { note = 56, canon = "crash.1.mute" },
  { note = 57, canon = "crash.1.hit", primary = true },
  { note = 58, canon = "crash.2.mute" },
  { note = 59, canon = "crash.2.hit", primary = true },
  { note = 60, canon = "crash.3.hit", primary = true },
  { note = 61, canon = "crash.3.mute" },
  { note = 62, canon = "splash.1.hit", primary = true },
  { note = 63, canon = "china.1.mute" },
  { note = 64, canon = "china.1.hit", primary = true },
  { note = 65, canon = "ride.1.bowtip", primary = true },
  { note = 66, canon = "ride.1.bell", primary = true },
  { note = 67, canon = "ride.1", primary = true },
  { note = 68, canon = "ride.1.edge", primary = true },
]
