id = "ggd_modernmassive"
name = "GGD Modern & Massive (Default Mapping 'Halpern')"
notes = [
  { note = 24, canon = "kick.main", primary = true },
  { note = 26, canon = "snare1.hit", primary = true },
  { note = 27, canon = "snare1.flam", primary = true },
  { note = 28, canon = "snare1.ruff", primary = true },
  { note = 29, canon = "snare1.off", primary = true },
  { note = 30, canon = "snare1.sidestick", primary = true },
  { note = 33, canon = "tom.rack1.hit", primary = true },
  { note = 37, canon = "tom.floor1.hit", primary = true },
  { note = 39, canon = "tom.floor2.hit", primary = true },
  { note = 43, canon = "hat.pedal", primary = true },
  { note = 45, canon = "hat.tight", primary = true },
  { note = 47, canon = "hat.closed", primary = true },
  { note = 48, canon = "hat.loose", primary = true },
  { note = 53, canon = "hat.open1", primary = true },
  { note = 54, canon = "hat.open2", primary = true },
  { note = 56, canon = "hat.open3", primary = true },
  { note = 58, canon = "hat.open4", primary = true },
  { note = 62, canon = "crash.1.hit", primary = true },
  { note = 64, canon = "crash.1.mute", primary = true },
  { note = 67, canon = "crash.2.hit", primary = true },
  { note = 69, canon = "crash.2.mute", primary = true },
  { note = 72, canon = "ride.1", primary = true },
  { note = 73, canon = "ride.1.edge", primary = true },
  { note = 74, canon = "ride.1.bell", primary = true },
  { note = 76, canon = "china.1.hit", primary = true },
  { note = 77, canon = "china.1.mute", primary = true },
  { note = 82, canon = "splash.1.mute", primary = true },
  { note = 83, canon = "splash.1.hit", primary = true },
]
