id = "ggd_invasion_ggd"
name = "GGD Invasion (Mapping 'GGD')"
notes = [
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.hit", primary = true },
  { note = 38, canon = "snare1.flam", primary = true },
  { note = 39, canon = "snare1.ruff", primary = true },
  { note = 40, canon = "snare1.sidestick", primary = true },
  { note = 41, canon = "snare1.off", primary = true },
  { note = 42, canon = "tom.rack1.hit", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 46, canon = "tom.floor2.hit", primary = true },
  { note = 48, canon = "hat.tight.tip", primary = true },
  { note = 49, canon = "hat.closed.tip", primary = true },
  { note = 52, canon = "hat.open1", primary = true },
  { note = 53, canon = "hat.open2", primary = true },
  { note = 54, canon = "hat.tight.edge", primary = true },
  { note = 55, canon = "hat.pedal", primary = true },
  { note = 57, canon = "hat.open3", primary = true },
  { note = 58, canon = "crash.2.hit", primary = true },
  { note = 59, canon = "crash.2.mute", primary = true },
  { note = 61, canon = "crash.1.hit", primary = true },
  { note = 62, canon = "crash.1.mute", primary = true },
  { note = 71, canon = "china.1.hit", primary = true },
  { note = 72, canon = "china.1.mute", primary = true },
  { note = 73, canon = "ride.1", primary = true },
  { note = 74, canon = "ride.1.bell", primary = true },
  { note = 76, canon = "ride.1.edge", primary = true },
  { note = 77, canon = "splash.1.hit", primary = true },
  { note = 83, canon = "splash.1.mute", primary = true },
]
