id = "ggd_halpern_ggd"
name = "GetGood Drums Matt Halpern (Mapping 'GGD')"
notes = [
  { note = 34, canon = "tom.floor1.rim", primary = true },
  { note = 35, canon = "tom.rack3.rim", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.hit", primary = true },
  { note = 38, canon = "snare1.flam", primary = true },
  { note = 39, canon = "snare1.ruff", primary = true },
  { note = 40, canon = "snare1.sidestick", primary = true },
  { note = 41, canon = "snare1.off", primary = true },
  { note = 42, canon = "tom.rack1.hit", primary = true },
  { note = 43, canon = "tom.rack2.hit", primary = true },
  { note = 45, canon = "tom.rack3.hit", primary = true },
  { note = 46, canon = "tom.floor1.hit", primary = true },
  { note = 48, canon = "hat.tight.tip", primary = true },
  { note = 49, canon = "hat.closed.tip", primary = true },
  { note = 50, canon = "hat.loose.edge", primary = true },
  { note = 51, canon = "hat.open1.edge", primary = true },
  { note = 52, canon = "hat.open2.edge", primary = true },
  { note = 53, canon = "hat.open3.edge", primary = true },
  { note = 54, canon = "hat.open4.edge", primary = true },
  { note = 55, canon = "hat.pedal", primary = true },
  { note = 57, canon = "hat.pedalsplash", primary = true },
  { note = 58, canon = "crash.1.hit", primary = true },
  { note = 59, canon = "crash.1.mute", primary = true },
  { note = 60, canon = "crash.1.hit" },
  { note = 61, canon = "crash.2.hit", primary = true },
  { note = 62, canon = "crash.2.mute", primary = true },
  { note = 63, canon = "crash.2.hit" },
  { note = 71, canon = "china.1.hit", primary = true },
  { note = 72, canon = "china.1.mute", primary = true },
  { note = 73, canon = "ride.1.bowtip", primary = true },
  { note = 74, canon = "ride.1.belltip", primary = true },
  { note = 75, canon = "ride.1.bell", primary = true },
  { note = 76, canon = "ride.1.edge", primary = true },
  { note = 77, canon = "splash.1.hit", primary = true },
  { note = 82, canon = "stack.1.hit", primary = true },
  { note = 83, canon = "stack.1.hit" },
  { note = 84, canon = "crash.1.bowtip", primary = true },
  { note = 85, canon = "crash.2.bowtip", primary = true },
]
