id = "ggd_poppunk"
name = "GGD One Kit Wonder: Pop Punk (Default Mapping 'Invasion')"
notes = [
  { note = 17, canon = "hat.cc", primary = true },
  { note = 24, canon = "kick.main", primary = true },
  { note = 26, canon = "snare1.hit", primary = true },
  { note = 30, canon = "snare1.sidestick", primary = true },
  { note = 33, canon = "tom.rack1.hit", primary = true },
  { note = 35, canon = "tom.floor1.hit", primary = true },
  { note = 41, canon = "hat.tight.tip", primary = true },
  { note = 42, canon = "hat.tight.edge", primary = true },
  { note = 43, canon = "hat.closed.tip", primary = true },
  { note = 44, canon = "hat.closed.edge", primary = true },
  { note = 45, canon = "hat.open1", primary = true },
  { note = 46, canon = "hat.open2", primary = true },
  { note = 47, canon = "hat.open3", primary = true },
  { note = 48, canon = "hat.pedal", primary = true },
  { note = 52, canon = "crash.1.hit", primary = true },
  { note = 53, canon = "crash.1.mute", primary = true },
  { note = 58, canon = "crash.2.hit", primary = true },
  { note = 59, canon = "crash.2.mute", primary = true },
  { note = 61, canon = "ride.1.bell", primary = true },
  { note = 62, canon = "ride.1", primary = true },
  { note = 63, canon = "ride.1.edge", primary = true },
  { note = 64, canon = "ride.1.mute", primary = true },
  { note = 65, canon = "china.1.hit", primary = true },
  { note = 66, canon = "china.1.mute", primary = true },
  { note = 73, canon = "splash.1.hit", primary = true },
  { note = 74, canon = "splash.1.mute", primary = true },
]
