id = "ggd_grooveplayer"
name = "GGD Groove Player/MIDI Pack Format"
notes = [
  { note = 5, canon = "hat.open3" },
  { note = 10, canon = "hat.closed.tip", primary = true },
  { note = 24, canon = "hat.closed.edge" },
  { note = 25, canon = "hat.open1" },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "snare1.ruff", primary = true },
  { note = 41, canon = "tom.floor2.hit", primary = true },
  { note = 42, canon = "hat.tight.edge", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 46, canon = "hat.open2", primary = true },
  { note = 48, canon = "tom.rack2.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "tom.rack1.hit", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "hat.closed.edge", primary = true },
  { note = 55, canon = "splash.1.hit", primary = true },
  { note = 56, canon = "aux1.open1", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 58, canon = "hat.open1", primary = true },
  { note = 59, canon = "ride.1.edge", primary = true },
  { note = 60, canon = "hat.open2" },
  { note = 62, canon = "hat.tight.tip", primary = true },
  { note = 64, canon = "splash.2.hit", primary = true },
  { note = 66, canon = "crash.1.mute", primary = true },
  { note = 69, canon = "snare1.flam", primary = true },
  { note = 70, canon = "hat.open3", primary = true },
  { note = 74, canon = "china.2.hit", primary = true },
  { note = 75, canon = "stack.1.hit", primary = true },
  { note = 95, canon = "crash.2.mute", primary = true },
]
