id = "goran_grooves_handy"
name = "Goran Grooves Handy Drums"
notes = [
  { note = 31, canon = "hat.cc.tip", primary = true },
  { note = 33, canon = "hat.cc.edge", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "perc.clap", primary = true },
  { note = 40, canon = "snare1.hit" },
  { note = 42, canon = "hat.closed.edge", primary = true },
  { note = 43, canon = "tom.floor2.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 45, canon = "tom.floor1.hit", primary = true },
  { note = 46, canon = "hat.open3", primary = true },
  { note = 47, canon = "hat.pedalsplash", primary = true },
  { note = 48, canon = "tom.rack2.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "tom.rack1.hit", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "perc.tambourine", primary = true },
  { note = 55, canon = "splash.1.hit", primary = true },
  { note = 56, canon = "perc.cowbell", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 59, canon = "splash.2.hit", primary = true },
  { note = 60, canon = "perc.misc" },
  { note = 61, canon = "perc.misc" },
  { note = 62, canon = "perc.misc" },
  { note = 63, canon = "perc.misc" },
  { note = 64, canon = "perc.misc" },
  { note = 65, canon = "perc.misc" },
  { note = 66, canon = "perc.misc" },
  { note = 67, canon = "perc.misc" },
  { note = 68, canon = "perc.misc" },
  { note = 69, canon = "perc.misc" },
  { note = 70, canon = "perc.misc" },
  { note = 71, canon = "perc.misc" },
  { note = 72, canon = "perc.misc" },
  { note = 73, canon = "perc.misc", primary = true },
  { note = 74, canon = "perc.misc" },
  { note = 75, canon = "perc.misc" },
  { note = 76, canon = "perc.misc" },
  { note = 77, canon = "perc.misc" },
  { note = 78, canon = "perc.misc" },
  { note = 79, canon = "perc.misc" },
  { note = 80, canon = "perc.misc" },
  { note = 81, canon = "perc.misc" },
  { note = 82, canon = "perc.shaker", primary = true },
  { note = 83, canon = "perc.misc" },
  { note = 85, canon = "perc.misc" },
  { note = 90, canon = "perc.misc" },
]
