id = "hertz2"
name = "Hertz Drums 2"
notes = [
  { note = 5, canon = "snare1.sidestick", primary = true },
  { note = 10, canon = "snare1.rimshot", primary = true },
  { note = 11, canon = "snare1.hit", primary = true },
  { note = 12, canon = "snare1.hit" },
  { note = 13, canon = "hat.closed", primary = true },
  { note = 14, canon = "hat.tight.tip", primary = true },
  { note = 15, canon = "hat.open5.bell", primary = true },
  { note = 16, canon = "hat.open5.tip", primary = true },
  { note = 17, canon = "hat.pedalsplash", primary = true },
  { note = 18, canon = "hat.cc", primary = true },
  { note = 19, canon = "hat.cc.edge", primary = true },
  { note = 20, canon = "hat.cc" },
  { note = 21, canon = "hat.pedal", primary = true },
  { note = 22, canon = "hat.closed.edge", primary = true },
  { note = 23, canon = "hat.tight.edge", primary = true },
  { note = 24, canon = "hat.open1", primary = true },
  { note = 25, canon = "hat.open2", primary = true },
  { note = 26, canon = "hat.open3", primary = true },
  { note = 27, canon = "hat.open4", primary = true },
  { note = 29, canon = "ride.1", primary = true },
  { note = 30, canon = "ride.1.bowtip", primary = true },
  { note = 31, canon = "ride.1.bell", primary = true },
  { note = 32, canon = "ride.1.edge", primary = true },
  { note = 33, canon = "ride.1.mute", primary = true },
  { note = 35, canon = "kick.left", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick" },
  { note = 38, canon = "snare1.hit" },
  { note = 39, canon = "snare1.hit" },
  { note = 40, canon = "snare1.rimshot" },
  { note = 41, canon = "snare1.rimshot" },
  { note = 42, canon = "hat.closed.tip", primary = true },
  { note = 43, canon = "snare1.hit" },
  { note = 44, canon = "hat.pedal" },
  { note = 45, canon = "snare1.hit" },
  { note = 46, canon = "hat.open4" },
  { note = 47, canon = "tom.floor2.hit", primary = true },
  { note = 48, canon = "tom.floor2.hit" },
  { note = 49, canon = "tom.floor2.hit" },
  { note = 50, canon = "tom.floor1.hit", primary = true },
  { note = 51, canon = "tom.floor1.hit" },
  { note = 52, canon = "tom.floor1.hit" },
  { note = 53, canon = "tom.rack3.hit", primary = true },
  { note = 54, canon = "tom.rack3.hit" },
  { note = 55, canon = "tom.rack3.hit" },
  { note = 56, canon = "tom.rack2.hit", primary = true },
  { note = 57, canon = "tom.rack2.hit" },
  { note = 58, canon = "tom.rack2.hit" },
  { note = 59, canon = "tom.rack1.hit", primary = true },
  { note = 60, canon = "tom.rack1.hit" },
  { note = 61, canon = "tom.rack1.hit" },
  { note = 62, canon = "crash.3.bowtip", primary = true },
  { note = 63, canon = "crash.3.hit", primary = true },
  { note = 64, canon = "crash.3.mute", primary = true },
  { note = 65, canon = "crash.2.bowtip", primary = true },
  { note = 66, canon = "crash.2.hit", primary = true },
  { note = 67, canon = "crash.2.mute", primary = true },
  { note = 68, canon = "crash.1.bowtip", primary = true },
  { note = 69, canon = "crash.1.hit", primary = true },
  { note = 70, canon = "crash.1.mute", primary = true },
  { note = 71, canon = "china.2.hit", primary = true },
  { note = 72, canon = "china.2.mute", primary = true },
  { note = 73, canon = "china.1.hit", primary = true },
  { note = 74, canon = "china.1.mute", primary = true },
  { note = 75, canon = "splash.3.hit", primary = true },
  { note = 76, canon = "splash.3.hit" },
  { note = 77, canon = "splash.3.mute", primary = true },
  { note = 78, canon = "splash.2.hit", primary = true },
  { note = 79, canon = "splash.2.hit" },
  { note = 80, canon = "splash.2.mute", primary = true },
  { note = 81, canon = "splash.1.hit", primary = true },
  { note = 82, canon = "splash.1.hit" },
  { note = 83, canon = "splash.1.mute", primary = true },
  { note = 102, canon = "tom.floor2.hit" },
  { note = 103, canon = "tom.floor2.hit" },
  { note = 104, canon = "tom.floor2.hit" },
  { note = 105, canon = "tom.floor1.hit" },
  { note = 106, canon = "tom.floor1.hit" },
  { note = 107, canon = "tom.floor1.hit" },
  { note = 108, canon = "tom.rack3.hit" },
  { note = 109, canon = "tom.rack3.hit" },
  { note = 110, canon = "tom.rack3.hit" },
  { note = 111, canon = "tom.rack2.hit" },
  { note = 112, canon = "tom.rack2.hit" },
  { note = 113, canon = "tom.rack2.hit" },
  { note = 114, canon = "tom.rack1.hit" },
  { note = 115, canon = "tom.rack1.hit" },
  { note = 116, canon = "tom.rack1.hit" },
]
