id = "mixwave_pridgen"
name = "MixWave Thomas Pridgen Drums"
notes = [
  { note = 17, canon = "tom.floor2.rim", primary = true },
  { note = 19, canon = "tom.floor1.rim", primary = true },
  { note = 21, canon = "tom.rack2.rim", primary = true },
  { note = 23, canon = "tom.rack1.rim", primary = true },
  { note = 25, canon = "snare1.ruff", primary = true },
  { note = 26, canon = "snare1.off", primary = true },
  { note = 31, canon = "perc.sticks", primary = true },
  { note = 32, canon = "hat.cc", primary = true },
  { note = 35, canon = "kick.main" },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 40, canon = "snare1.hit" },
  { note = 41, canon = "tom.floor2.hit", primary = true },
  { note = 42, canon = "hat.closed.tip", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 45, canon = "tom.rack2.hit" },
  { note = 46, canon = "hat.open2", primary = true },
  { note = 47, canon = "tom.rack2.hit", primary = true },
  { note = 48, canon = "tom.rack1.hit" },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "tom.rack1.hit", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "crash.3.hit", primary = true },
  { note = 55, canon = "splash.1.hit", primary = true },
  { note = 56, canon = "stack.1.hit", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 58, canon = "stack.2.hit", primary = true },
  { note = 59, canon = "ride.1.edge", primary = true },
  { note = 61, canon = "crash.1.mute", primary = true },
  { note = 62, canon = "aux1.open1", primary = true },
  { note = 63, canon = "aux1.open1" },
  { note = 64, canon = "aux1.open1" },
  { note = 65, canon = "aux1.open1" },
  { note = 66, canon = "crash.3.mute", primary = true },
  { note = 67, canon = "stack.3.hit", primary = true },
  { note = 69, canon = "crash.2.mute", primary = true },
  { note = 71, canon = "ride.1.mute", primary = true },
  { note = 74, canon = "hat.tight.tip", primary = true },
  { note = 75, canon = "hat.closed.tip" },
  { note = 76, canon = "hat.closed.edge", primary = true },
  { note = 77, canon = "hat.open1", primary = true },
  { note = 78, canon = "hat.open2" },
  { note = 79, canon = "hat.open3", primary = true },
  { note = 80, canon = "hat.pedal" },
  { note = 81, canon = "hat.pedalsplash", primary = true },
  { note = 91, canon = "crash.1.hit" },
  { note = 92, canon = "crash.1.mute" },
  { note = 93, canon = "crash.2.hit" },
  { note = 94, canon = "crash.2.mute" },
  { note = 98, canon = "splash.1.hit" },
  { note = 99, canon = "splash.1.mute", primary = true },
  { note = 100, canon = "china.1.hit" },
  { note = 101, canon = "china.1.mute", primary = true },
]
