id = "mixwave_fang"
name = "MixWave Turnstile Daniel Fang"
notes = [
  { note = 5, canon = "tom.rack1.hit", primary = true },
  { note = 6, canon = "tom.rack1.rimshot", primary = true },
  { note = 7, canon = "tom.rack1.hit" },
  { note = 8, canon = "tom.rack1.rim", primary = true },
  { note = 9, canon = "tom.rack2.hit", primary = true },
  { note = 10, canon = "tom.rack2.rimshot", primary = true },
  { note = 11, canon = "tom.rack2.hit" },
  { note = 12, canon = "tom.rack2.rim", primary = true },
  { note = 17, canon = "tom.floor1.rim", primary = true },
  { note = 21, canon = "tom.rack3.rim", primary = true },
  { note = 25, canon = "snare1.ruff", primary = true },
  { note = 27, canon = "snare1.flam", primary = true },
  { note = 31, canon = "perc.sticks", primary = true },
  { note = 32, canon = "hat.cc.edge", primary = true },
  { note = 33, canon = "hat.cc.tip", primary = true },
  { note = 35, canon = "kick.main" },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "perc.clap", primary = true },
  { note = 40, canon = "snare1.hit" },
  { note = 41, canon = "tom.floor1.hit" },
  { note = 42, canon = "hat.closed.edge", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 45, canon = "tom.rack3.hit" },
  { note = 46, canon = "hat.open3.edge", primary = true },
  { note = 47, canon = "tom.rack3.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "crash.3.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 55, canon = "stack.1.hit", primary = true },
  { note = 56, canon = "stack.1.hit" },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 59, canon = "ride.1.edge", primary = true },
  { note = 61, canon = "crash.1.mute", primary = true },
  { note = 64, canon = "crash.3.mute", primary = true },
  { note = 69, canon = "crash.2.mute", primary = true },
  { note = 71, canon = "ride.1.mute", primary = true },
  { note = 73, canon = "hat.tight.tip", primary = true },
  { note = 74, canon = "hat.tight.edge", primary = true },
  { note = 75, canon = "hat.closed.tip", primary = true },
  { note = 76, canon = "hat.closed.edge" },
  { note = 77, canon = "hat.open1.edge", primary = true },
  { note = 78, canon = "hat.open2.edge", primary = true },
  { note = 79, canon = "hat.open3.edge" },
  { note = 81, canon = "hat.pedalsplash", primary = true },
  { note = 83, canon = "hat.open1.tip", primary = true },
  { note = 84, canon = "hat.open2.tip", primary = true },
  { note = 85, canon = "hat.open3.tip", primary = true },
  { note = 90, canon = "crash.1.hit" },
  { note = 91, canon = "crash.1.mute" },
  { note = 92, canon = "crash.2.hit" },
  { note = 93, canon = "crash.2.mute" },
  { note = 100, canon = "crash.3.hit" },
  { note = 101, canon = "crash.3.mute" },
  { note = 108, canon = "perc.cowbell", primary = true },
  { note = 109, canon = "perc.cowbell" },
  { note = 110, canon = "perc.cowbell" },
  { note = 111, canon = "perc.cowbell" },
  { note = 112, canon = "perc.misc", primary = true },
  { note = 113, canon = "perc.shaker", primary = true },
  { note = 114, canon = "perc.shaker" },
  { note = 115, canon = "perc.shaker" },
  { note = 116, canon = "perc.shaker" },
  { note = 120, canon = "perc.tambourine", primary = true },
  { note = 121, canon = "perc.tambourine" },
  { note = 122, canon = "perc.tambourine" },
  { note = 123, canon = "perc.tambourine" },
]
