id = "odeholm"
name = "Odeholm Drums"
notes = [
  { note = 35, canon = "kick.left", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "snare1.flam", primary = true },
  { note = 41, canon = "tom.floor1.hit", primary = true },
  { note = 43, canon = "tom.floor2.hit", primary = true },
  { note = 45, canon = "tom.rack2.hit", primary = true },
  { note = 47, canon = "tom.rack1.hit", primary = true },
  { note = 48, canon = "hat.open3", primary = true },
  { note = 49, canon = "hat.open2", primary = true },
  { note = 50, canon = "hat.open1", primary = true },
  { note = 51, canon = "hat.closed.tip", primary = true },
  { note = 52, canon = "hat.closed.edge", primary = true },
  { note = 53, canon = "hat.pedal", primary = true },
  { note = 54, canon = "crash.1.hit", primary = true },
  { note = 55, canon = "crash.1.mute", primary = true },
  { note = 56, canon = "crash.2.hit", primary = true },
  { note = 57, canon = "crash.2.mute", primary = true },
  { note = 58, canon = "ride.1.bowtip", primary = true },
  { note = 59, canon = "ride.1.bell", primary = true },
  { note = 60, canon = "ride.1.edge", primary = true },
  { note = 61, canon = "crash.3.hit", primary = true },
  { note = 62, canon = "crash.3.mute", primary = true },
  { note = 63, canon = "china.1.hit", primary = true },
  { note = 64, canon = "china.1.mute", primary = true },
  { note = 65, canon = "china.2.hit", primary = true },
  { note = 66, canon = "china.2.mute", primary = true },
  { note = 67, canon = "stack.1.hit", primary = true },
  { note = 68, canon = "splash.1.hit", primary = true },
  { note = 69, canon = "splash.1.mute", primary = true },
  { note = 70, canon = "splash.2.hit", primary = true },
  { note = 71, canon = "splash.2.mute", primary = true },
  { note = 72, canon = "bell.1.hit", primary = true },
  { note = 73, canon = "bell.1.mute", primary = true },
]
