id = "redpack_dsdrum"
name = "Red Pack Drums: DS Drum"
notes = [
  { note = 21, canon = "hat.pedal" },
  { note = 22, canon = "hat.closed.edge", primary = true },
  { note = 24, canon = "hat.open1" },
  { note = 25, canon = "hat.open2" },
  { note = 33, canon = "snare1.rimshot" },
  { note = 34, canon = "kick.main" },
  { note = 35, canon = "perc.sticks", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 37, canon = "snare1.sidestick", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 39, canon = "perc.sticks" },
  { note = 40, canon = "snare1.rimshot", primary = true },
  { note = 41, canon = "tom.floor2.hit", primary = true },
  { note = 42, canon = "hat.closed.tip", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 47, canon = "tom.rack2.hit", primary = true },
  { note = 48, canon = "tom.rack1.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "crash.1.mute", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "splash.1.mute", primary = true },
  { note = 55, canon = "splash.1.hit", primary = true },
  { note = 56, canon = "crash.2.mute", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 58, canon = "china.1.mute", primary = true },
  { note = 59, canon = "ride.1.edge", primary = true },
  { note = 60, canon = "hat.closed.edge" },
  { note = 61, canon = "hat.closed.tip" },
  { note = 62, canon = "hat.tight.edge", primary = true },
  { note = 63, canon = "hat.tight.tip", primary = true },
  { note = 64, canon = "hat.open2", primary = true },
  { note = 65, canon = "hat.open1", primary = true },
  { note = 66, canon = "snare1.off", primary = true },
  { note = 67, canon = "hat.open3", primary = true },
  { note = 68, canon = "snare1.hit" },
  { note = 69, canon = "snare1.flam", primary = true },
  { note = 71, canon = "snare1.sidestick" },
  { note = 91, canon = "ride.1.edge" },
  { note = 102, canon = "ride.1.bell" },
  { note = 104, canon = "ride.1" },
]
