id = "soundblind_counterkit"
name = "Soundblind Drums Counterkit"
notes = [
  { note = 36, canon = "kick.main", primary = true },
  { note = 39, canon = "snare1.hit", primary = true },
  { note = 40, canon = "snare1.rim", primary = true },
  { note = 43, canon = "tom.floor1.hit", primary = true },
  { note = 45, canon = "tom.rack1.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "crash.1.mute", primary = true },
  { note = 51, canon = "ride.1", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "china.1.mute", primary = true },
  { note = 55, canon = "ride.2", primary = true },
  { note = 56, canon = "ride.2.bell", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 58, canon = "crash.2.mute", primary = true },
  { note = 59, canon = "ride.1.edge", primary = true },
  { note = 60, canon = "hat.open3", primary = true },
  { note = 61, canon = "hat.closed.edge", primary = true },
  { note = 62, canon = "hat.closed.tip", primary = true },
  { note = 63, canon = "hat.pedal", primary = true },
  { note = 64, canon = "hat.closed", primary = true },
  { note = 65, canon = "hat.closed" },
]
