id = "ugritone"
name = "Ugritone Drums"
notes = [
  { note = 32, canon = "hat.open5", primary = true },
  { note = 36, canon = "kick.main", primary = true },
  { note = 38, canon = "snare1.hit", primary = true },
  { note = 41, canon = "tom.floor1.hit", primary = true },
  { note = 42, canon = "hat.closed", primary = true },
  { note = 43, canon = "tom.rack4.hit", primary = true },
  { note = 44, canon = "hat.pedal", primary = true },
  { note = 45, canon = "tom.rack3.hit", primary = true },
  { note = 46, canon = "hat.loose", primary = true },
  { note = 47, canon = "tom.rack2.hit", primary = true },
  { note = 48, canon = "tom.rack1.hit", primary = true },
  { note = 49, canon = "crash.1.hit", primary = true },
  { note = 50, canon = "crash.1.mute", primary = true },
  { note = 51, canon = "ride.1.bowtip", primary = true },
  { note = 52, canon = "china.1.hit", primary = true },
  { note = 53, canon = "ride.1.bell", primary = true },
  { note = 54, canon = "ride.1.edge", primary = true },
  { note = 55, canon = "splash.1.hit", primary = true },
  { note = 56, canon = "bell.1.hit", primary = true },
  { note = 57, canon = "crash.2.hit", primary = true },
  { note = 58, canon = "crash.2.mute", primary = true },
  { note = 59, canon = "bell.2.hit", primary = true },
  { note = 61, canon = "china.2.hit", primary = true },
]
